export const DoctorData = [{
    "id": 1,
    "name": "Dr. John Doe",
    "speciality": "General Physician",
    "qualification": "MBBS, MD (Orthopedic)",
    "experience": "25 Years Experience",
    "url": "https://images.pexels.com/photos/3714743/pexels-photo-3714743.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}, {
    "id": 2,
    "name": "Dr. Jane Smith",
    "speciality": "Cardiologist",
    "qualification": "MD (Cardiology), DNB (Cardio Thoracic & Vascular) ",
    "experience": "18 Years Experience",
}, {
    "id": 3,
    "name": "Dr. Peter Parker",
    "speciality": "Neurologist",
    "qualification": "MD (Neurosurgery), DM (Neurology & Psychiatry) ",
    "experience": "12 Years Experience",
}, {
    "id": 4,
    "name": "Dr. Lisa Nardini",
    "speciality": "Urologist",
    "qualification": "MD (Urology), FRCSI (Fellow of the Royal College of Surgeons in Ireland) ",
    "experience": "7 Years Experience",
}, {
    "id": 5,
    "name": "Dr. James Wilson",
    "speciality": "Dermatologist",
    "qualification": "MBChB (Londonderry Medical School, University of London), FRCOG (Fellow of the Royal College of Obstetricians and Gynaec",
    "experience": "15 Years Experience",
}, {
    "id": 6,
    "name": "Dr. Mary Johnson",
    "speciality": "Ophthalmologist",
    "qualification": "MD (Cardiology), DNB (Cardio Thoracic & Vascular)",
    "experience": "20 Years Experience",
}, {
    "id": 7,
    "name": "Dr. William Davis",
    "speciality": "Psychiatrist",
    "qualification": "MD (Psychiatry & Clinical Neuroscience)",
    "experience": "20 Years Experience",
}, {
    "id": 8,
    "name": "Dr. Samantha Brown",
    "speciality": "Pediatrician",
    "qualification": "MD (Pediatrics), DCH (Diploma in Child Health)",
    "experience": "20 Years Experience",
}, {
    "id": 9,
    "name": "Dr. Alex Johnson",
    "speciality": "Gastroenterologist",
    "qualification": "MD (Gastroenterology), PhD in Digestive Sciences",
    "experience": "22 Years Experience",
}, {
    "id": 10,
    "name": "Dr. Emily Davis",
    "speciality": "Psychiatrist",
    "qualification": "MD (Psychiatry), Board Certified in Child & Adolescent Psychiatry",
    "experience": "14 Years Experience",
}, {
    "id": 11,
    "name": "Dr. William Chang",
    "speciality": "Oncologist",
    "qualification": "MD (Oncology), Fellowship in Hematology-Oncology",
    "experience": "10 Years Experience",
}, {
    "id": 12,
    "name": "Dr. Michaela Garcia",
    "speciality": "Endocrinologist",
    "qualification": "MD (Endocrinology), Certified Diabetes Educator",
    "experience": "18 Years Experience",
}, {
    "id": 13,
    "name": "Dr. Emily Johnson",
    "speciality": "Pediatrician",
    "qualification": "MBBS, MD (Pediatrics)",
    "experience": "20 Years Experience",
}, {
    "id": 14,
    "name": "Dr. Michael Chang",
    "speciality": "Cardiologist",
    "qualification": "MD (Cardiology), PhD",
    "experience": "22 Years Experience",
}, {
    "id": 15,
    "name": "Dr. Rachel Lee",
    "speciality": "Neurologist",
    "qualification": "MD (Neurology), DM (Neurosurgery)",
    "experience": "15 Years Experience",
}, {
    "id": 16,
    "name": "Dr. Lisa Patel",
    "speciality": "Urologist",
    "qualification": "MD (Urology), FRCS",
    "experience": "10 Years Experience",
}, {
    "id": 17,
    "name": "Dr. David Miller",
    "speciality": "Dermatologist",
    "qualification": "MBChB (University of London), FRCGP (Fellow of the Royal College of General Practitioners)",
    "experience": "18 Years Experience",
}, {
    "id": 18,
    "name": "Dr. Emily Brown",
    "speciality": "Pediatrician",
    "qualification": "MBBS, MD (Pediatrics)",
    "experience": "20 Years Experience",
}, {
    "id": 19,
    "name": "Dr. Alexander Johnson",
    "speciality": "Oncologist",
    "qualification": "MD (Oncology), PhD (Cancer Research)",
    "experience": "22 Years Experience",
}, {
    "id": 20,
    "name": "Dr. Samantha White",
    "speciality": "Psychiatrist",
    "qualification": "MD (Psychiatry), MS (Clinical Psychology)",
    "experience": "15 Years Experience",
}, {
    "id": 21,
    "name": "Dr. Michael Chen",
    "speciality": "Orthopedic Surgeon",
    "qualification": "MD (Orthopedic Surgery), Fellowship in Sports Medicine",
    "experience": "8 Years Experience",
}, {
    "id": 22,
    "name": "Dr. Olivia Taylor",
    "speciality": "Endocrinologist",
    "qualification": "MD (Endocrinology), DSc (Endocrine Research)",
    "experience": "18 Years Experience",
}, {
    "id": 23,
    "name": "Dr. Elizabeth Nguyen",
    "speciality": "Gastroenterologist",
    "qualification": "MD (Gastroenterology), Fellowship in Advanced Endoscopy",
    "experience": "12 Years Experience",
}, {
    "id": 24,
    "name": "Dr. Alex Williams",
    "speciality": "Oncologist",
    "qualification": "MD (Oncology), PhD (Cancer Research)",
    "experience": "22 Years Experience",
}, {
    "id": 25,
    "name": "Dr. Sophia Lee",
    "speciality": "Psychiatrist",
    "qualification": "MD (Psychiatry), DPsych (Clinical Psychology)",
    "experience": "16 Years Experience",
}, {
    "id": 26,
    "name": "Dr. Michael Brown",
    "speciality": "Orthopedic Surgeon",
    "qualification": "MD (Orthopedics), FRCS (Fellow of the Royal College of Surgeons)",
    "experience": "12 Years Experience",
}, {
    "id": 27,
    "name": "Dr. Rachel Nguyen",
    "speciality": "Gastroenterologist",
    "qualification": "MD (Gastroenterology), MRCP (Member of the Royal College of Physicians)",
    "experience": "10 Years Experience",
}, {
    "id": 28,
    "name": "Dr. Elizabeth Johnson",
    "speciality": "Pediatrician",
    "qualification": "MD (Pediatrics), MPH (Master of Public Health)",
    "experience": "20 Years Experience",
}, {
    "id": 29,
    "name": "Dr. William Brown",
    "speciality": "Gastroenterologist",
    "qualification": "MD (Gastroenterology), PhD (Nutritional Sciences)",
    "experience": "22 Years Experience",
}, {
    "id": 30,
    "name": "Dr. Sarah Anderson",
    "speciality": "Psychiatrist",
    "qualification": "MD (Psychiatry), DPM (Doctor of Podiatric Medicine)",
    "experience": "14 Years Experience",
}, {
    "id": 31,
    "name": "Dr. Michael Smith",
    "speciality": "Orthopedic Surgeon",
    "qualification": "MD (Orthopedic Surgery), FRCS (Fellow of the Royal College of Surgeons)",
    "experience": "10 Years Experience",
}, {
    "id": 32,
    "name": "Dr. Emily Taylor",
    "speciality": "Oncologist",
    "qualification": "MD (Oncology), MS (Medical Oncology)",
    "experience": "18 Years Experience",
}, {
    "id": 33,
    "name": "Dr. James Wilson",
    "speciality": "Cardiologist",
    "qualification": "MBBS (Bachelor of Medicine and Bachelor of Surgery), MD (Cardiology)",
    "experience": "18 Years Experience",
}, {
    "id": 34,
    "name": "Dr. Robert Cook",
    "speciality": "Neurologist",
    "qualification": "MBBS (Bachelor of Medicine and Bachelor of Surgery), MD (Neurosciences)",
    "experience": "15 Years Experience",
}, {
    "id": 35,
    "name": "Dr. Julia Johnson",
    "speciality": "Urologist",
    "qualification": "MBBS (Bachelor of Medicine and Bachelor of Surgery)",
    "experience": "18 Years Experience",
}, {
    "id": 36,
    "name": "Nurse Annie Edison",
    "speciality": "Oncologist",
    "qualification": "MD (Oncology), MS (Medical Oncology)",
    "experience": "18 Years Experience",
}, {
    "id": 37,
    "name": "Dr. Benjamin Adams",
    "speciality": "Endocrinologist",
    "qualification": "MD (Endocrinology), FACE (Fellow of the American College of Endocrinology)",
    "experience": "18 Years Experience",
}, {
    "id": 38,
    "name": "Dr. Elizabeth Carter",
    "speciality": "Pulmonologist",
    "qualification": "MD (Pulmonology), FCCP (Fellow of the American College of Chest Physicians)",
    "experience": "15 Years Experience",
}, {
    "id": 39,
    "name": "Dr. Christopher Martinez",
    "speciality": "Neonatologist",
    "qualification": "MD (Neonatology), NRP (Neonatal Resuscitation Program)",
    "experience": "12 Years Experience",
}, {
    "id": 40,
    "name": "Dr. Sophia Nguyen",
    "speciality": "Rheumatologist",
    "qualification": "MD (Rheumatology), ACR (American College of Rheumatology) Certified",
    "experience": "20 Years Experience",
}]